STACK 	SEGMENT 
		DW 32 DUP(0)
STACK   ENDS		
CODE 	SEGMENT
		ASSUME	CS:CODE
START	PROC FAR
		MOV AX,8000H		;基址
		MOV DS,AX
AA0:	MOV SI,0000H		;偏移地址
		MOV CX,0010H		;CX中放的是循环次数 16次
		MOV AX,0000H		;AX中放的是要存入的数据
AA1:	MOV [SI],AX
		INC AX
		INC SI
		INC SI
		LOOP AA1
		MOV AH,4CH
		INT 21H
START 	ENDP
CODE 	ENDS
		END START
		